name: 'ms-v-cust-ws'
services:

  postgres:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=testdb'
      - 'POSTGRES_USER=testuser'
      - 'POSTGRES_PASSWORD=testpass'
    ports:
      - "5432"
    volumes:
      - ./src/main/resources/db/create-table.sql:/docker-entrypoint-initdb.d/init.sql