name: 'ms-v-cust-ws'
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432"
    volumes:
      - ./src/main/resources/db/create-table-seed.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ms-v-cust-network

networks:
  ms-v-cust-network:
    name: ms-v-cust-network